---

- name: App | Setting Folder Permissions
  command: chmod -R 755 /vagrant/app/storage

- name: App | Composer install
  command: composer install chdir=/vagrant

- name: App | install yo angular
  command: yo angular laravel chdir=/vagrant/public